version = 1
SPDX-PackageName = "github.com/sap-docs/preview.developer.concur.com"
SPDX-PackageSupplier = "barry.smith@sap.com"
SPDX-PackageDownloadLocation = "https://github.com/sap-docs/preview.developer.concur.com"

[[annotations]]
path = "**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2021 SAP SE or an SAP affiliate company and preview.developer.concur.com contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "Gemfile"
precedence = "aggregate"
SPDX-FileCopyrightText = "2013 Garen Torikian"
SPDX-License-Identifier = "MIT"
SPDX-FileComment = "This is an included gem in the Gemfile"

[[annotations]]
path = "Gemfile.lock"
precedence = "aggregate"
SPDX-FileCopyrightText = "2013 Garen Torikian"
SPDX-License-Identifier = "MIT"
SPDX-FileComment = "html-proofer 3.16.0"

[[annotations]]
path = "Gemfile"
precedence = "aggregate"
SPDX-FileCopyrightText = "2016 Ben Balter"
SPDX-License-Identifier = "MIT"
SPDX-FileComment = "This is an included gem in the Gemfile"

[[annotations]]
path = "Gemfile.lock"
precedence = "aggregate"
SPDX-FileCopyrightText = "2016 Ben Balter"
SPDX-License-Identifier = "MIT"
SPDX-FileComment = "jekyll-bootstrap-sass 0.1.0"

[[annotations]]
path = "Gemfile"
precedence = "aggregate"
SPDX-FileCopyrightText = "2013-present Parker Moore and jekyll-redirect-from contributors"
SPDX-License-Identifier = "MIT"
SPDX-FileComment = "This is an included gem in the Gemfile"

[[annotations]]
path = "Gemfile.lock"
precedence = "aggregate"
SPDX-FileCopyrightText = "2013-present Parker Moore and jekyll-redirect-from contributors"
SPDX-License-Identifier = "MIT"
SPDX-FileComment = "jekyll-bootstrap-sass 0.16.0"

[[annotations]]
path = "Gemfile"
precedence = "aggregate"
SPDX-FileCopyrightText = "2015 Brandon Mathis"
SPDX-License-Identifier = "MIT"
SPDX-FileComment = "This is an included gem in the Gemfile"

[[annotations]]
path = "Gemfile.lock"
precedence = "aggregate"
SPDX-FileCopyrightText = "2015 Brandon Mathis"
SPDX-License-Identifier = "MIT"
SPDX-FileComment = "octopress-paginate 1.2.0"

[[annotations]]
path = "Gemfile"
precedence = "aggregate"
SPDX-FileCopyrightText = "2006-2016 Hampton Catlin, Natalie Weizenbaum, and Chris Eppstein"
SPDX-License-Identifier = "MIT"
SPDX-FileComment = "This is an included gem in the Gemfile"

[[annotations]]
path = "Gemfile.lock"
precedence = "aggregate"
SPDX-FileCopyrightText = "2006-2016 Hampton Catlin, Natalie Weizenbaum, and Chris Eppstein"
SPDX-License-Identifier = "MIT"
SPDX-FileComment = "sass 3.7.4"
